# .gitlab-ci.yml

image: docker/compose:latest

services:
  - docker:dind

before_script:
  - docker version
  - docker-compose version

build:
  stage: build
  script:
    - cd gitlab
#    - docker-compose down
    - docker-compose build
#    - docker-compose up tester-image
